name: "Automated Fun Scraper and Sender"

on:
  schedule:
    - cron: '0 10 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
      - name: Install Dependencies # Using shell script to install Google Chrome
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute main script # run main.py to get the latest data
        run: python main.py